# Generated by Django 5.0 on 2024-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Название')),
                ('slug', models.CharField(verbose_name='djangodbmodelsfieldscharfield')),
                ('body', models.TextField(max_length=211, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, default='test', null=True, upload_to='media/', verbose_name='Превью')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('ispublished', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
