# Generated by Django 5.0 on 2023-12-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Наименование')),
                ('desc', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Наименование')),
                ('desc', models.CharField(max_length=90, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Превью')),
                ('category', models.CharField(max_length=50, verbose_name='категория')),
                ('price', models.IntegerField(max_length=10, verbose_name='Цена за штуку')),
                ('create_date', models.DateField(auto_now=True)),
                ('last_change', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
