# Generated by Django 5.0 on 2023-12-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_created_at_alter_category_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
