# Generated by Django 5.0 on 2024-01-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='test', null=True, upload_to='media/', verbose_name='Превью'),
        ),
    ]
